config/routes.rb
Rails.application.routes.draw do
  post 'data/upload_csv'
  get 'data/display'
  root to: 'data#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/csv_import.rb
module CSVImport
  extend ActiveSupport::Concern

  def process_data(csv_file_contents)
    begin
      csv_file_contents.each_with_index do |csv_file_content, i|
        mapping = Mapping.find_or_initialize_by(name: csv_file_content[:mapping])
        return [false, "Error while creating mapping #{mapping.errors.full_messages.join(', ')} on row number #{i + 2}"] if mapping.id.nil? && !mapping.save

        role = Role.find_or_initialize_by(name: csv_file_content[:role])
        return [false, "Error while creating role #{role.errors.full_messages.join(', ')} on row number #{i + 2}"] if role.id.nil? && !role.save

        question = Question.find_or_initialize_by(content: csv_file_content[:question], mapping_id: mapping.id, role_id: role.id)
        question.pri = csv_file_content[:pri].to_i
        question.teaming_stages = csv_file_content[:teaming_stages]
        question.appears = csv_file_content[:appears_day].to_i
        question.frequency = csv_file_content[:frequency].to_i
        question.question_type = csv_file_content[:type]
        question.is_required = (csv_file_content[:required].downcase == 'yes')
        question.conditions = csv_file_content[:conditions]
        return [false, "Error while creating question #{question.errors.full_messages.join(', ')} on row number #{i + 2}"] if !question.save
      end
    rescue Exception
      return [false, "Exception occured. Check CSV file format"]
    end

    [true, "Created all questions"]
  end
end

app/models/mapping.rb
class Mapping < ApplicationRecord
  extend CSVImport

  validates_presence_of :name
  validates_uniqueness_of :name

  has_many :questions
end

app/models/question.rb
class Question < ApplicationRecord
  validates_presence_of :content

  belongs_to :role
  belongs_to :mapping
end

app/models/role.rb
class Role < ApplicationRecord
  validates_presence_of :name
  validates_uniqueness_of :name

  has_many :questions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/data_controller.rb
require 'csv'

class DataController < ApplicationController
  def home
  end

  def upload_csv
    csv_text = params[:upload_csv_file].tempfile.read
    csv_file_contents = []
    CSV.parse(csv_text, headers: true, header_converters: :symbol).each do |row|
      csv_file_contents << row.to_hash
    end
    status, message = Mapping.process_data(csv_file_contents)

    render json: { message: message }, status: (status ? :ok : :bad_request)
  end

  def display
    questions = Question.includes(:mapping, :role)
    render locals: { questions: questions }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/data_helper.rb
module DataHelper
end

app/views/data/display.html.erb
<%= link_to 'Import CSV', root_path, class: "btn btn-primary", id: :importCSV %>

<table id='questionsTable' class='table table-responsive' width='100%'>
  <thead>
    <tr>
      <th>Pri</th>
      <th>Question</th>
      <th>Teaming Stages</th>
      <th>Appears (Day)</th>
      <th>Frequency</th>
      <th>Type</th>
      <th>Role</th>
      <th>Required?</th>
      <th>Conditions</th>
      <th>Mapping</th>
    </tr>
  </thead>
  <tbody>
    <% questions.each do |question| %>
      <tr>
        <td>
          <%= question.pri %>
        </td>
        <td>
          <%= question.content %>
        </td>
        <td>
          <%= question.teaming_stages %>
        </td>
        <td>
          <%= question.appears %>
        </td>
        <td>
          <%= question.frequency %>
        </td>
        <td>
          <%= question.question_type %>
        </td>
        <td>
          <%= question.role.name %>
        </td>
        <td>
          <%= question.is_required ? 'Yes' : 'No' %>
        </td>
        <td>
          <%= question.conditions %>
        </td>
        <td>
          <%= question.mapping.name %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/data/home.html.erb
<%= link_to 'Display Data', data_display_path, class: "btn btn-primary", id: :displayData %>
<%= form_with(url: {action: :upload_csv, method: :post}, multipart: true, remote: true, id: :uploadCSVForm) do %>
  <div class="input-group">
    <div class="input-group-prepend">
      <span class="input-group-text" id="uploadCSVAddOn">Upload</span>
    </div>

    <div class="custom-file">
      <%= file_field_tag 'upload_csv_file', class: "custom-file-input", "aria-describedby" => "uploadCSVAddOn", accept: '.csv', "data-url" => data_upload_csv_path %>
      <label class="custom-file-label" for="fileInput">Choose a CSV file...</label>
    </div>
  </div>

  <div class="input-group">
    <%= submit_tag 'Upload', class: "btn btn-success", id: :uploadCSVSubmit, disabled: true %>
  </div>
<% end %>

app/views/data/upload_csv.html.erb
<h1>Data#upload_csv</h1>
<p>Find me in app/views/data/upload_csv.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Questionnaire</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <h1>Upload & View Questionnaires</h1>
      <%= yield %>
    </div>
  </body>
</html>